#! /bin/bash
set -e

FILE="/tmp/output.txt"

cat > $FILE <<- EOM
Level: $ELKARBACKUP_LEVEL
Event: $ELKARBACKUP_EVENT
Url: $ELKARBACKUP_URL
Id: $ELKARBACKUP_ID
Path: $ELKARBACKUP_PATH
Status: $ELKARBACKUP_STATUS
Client-name: $ELKARBACKUP_CLIENT_NAME
Job-name: $ELKARBACKUP_JOB_NAME
Owner-email: $ELKARBACKUP_OWNER_EMAIL
EOM
